# Generated by Django 2.1.7 on 2019-08-30 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnh', models.CharField(max_length=50)),
                ('validade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PassagemAviao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companhiaAereaPartida', models.CharField(max_length=50)),
                ('numVooPartida', models.CharField(max_length=100)),
                ('companhiaAereaChegada', models.CharField(max_length=50)),
                ('numVooChegada', models.CharField(max_length=100)),
                ('horaPartida', models.CharField(max_length=100)),
                ('horaChegada', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('tipoUsuario', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Siape', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('diretor', models.TextField(blank=True, null=True, verbose_name='Setor')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=50)),
                ('ano', models.CharField(max_length=100)),
                ('quilometragem', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Viajem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePassageiros', models.CharField(max_length=100)),
                ('quantidadePassageiros', models.CharField(max_length=50)),
                ('finalidade', models.CharField(max_length=100)),
                ('roteiro', models.CharField(max_length=100)),
                ('dataPartida', models.CharField(max_length=8)),
                ('dataRetorno', models.CharField(max_length=8)),
                ('solicitante', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='adocao.Pessoa')),
            ],
        ),
    ]
