# Generated by Django 2.1.7 on 2019-08-30 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='senha',
        ),
    ]
